version: '2'
services:
  web:
    image: "whatevermarch/event-manager:latest"
    ports:
     - "7777:7777"
    volumes:
     - /app
     - /app/node_modules
  db:
    image: "mongo:latest"
    ports:
     - "27017:27017"
